import { useState, useMemo } from 'react';
import { useChatHistory, useUserEvents, eventButtonLabels, funnelStageLabels } from '../hooks/useApi';
import type { UserEvent } from '../../shared/types';
import { Button } from './ui/button';
import { MousePointerClick, Mail, Bot, ClipboardList } from 'lucide-react';

interface ChatHistoryProps {
  sessionId: string;
}

type TimelineItem =
  | { kind: 'message'; id: number; type: string; content: string; timestamp?: string }
  | { kind: 'event'; event: UserEvent }
  | { kind: 'button'; id: number; label: string };

const INITIAL_COUNT = 20;

// These messages are generated by callback buttons — display as button clicks
const CALLBACK_PHRASES: Record<string, string> = {
  'Да, всё верно, подтверждаю': 'Подтвердил данные',
  'Yes, everything is correct, I confirm': 'Confirmed data',
  'نعم، كل شيء صحيح، أؤكد': 'Confirmed data',
};

const dataLabels: Record<string, string> = {
  sex: 'Пол', weight: 'Вес', height: 'Рост', age: 'Возраст',
  activity_level: 'Активность', goal: 'Цель', allergies: 'Аллергии',
  excluded_foods: 'Исключения',
};

const valueLabels: Record<string, string> = {
  male: 'мужской', female: 'женский',
  weight_loss: 'похудение', weight_gain: 'набор массы',
  maintenance: 'поддержание', muscle_gain: 'набор мышц',
  sedentary: 'сидячий', light: 'лёгкая', moderate: 'умеренная',
  active: 'высокая', very_active: 'очень высокая',
  none: 'нет',
};

function formatJsonContent(content: string): { formatted: string; isJson: boolean } {
  const jsonMatch = content.match(/```json\s*([\s\S]*?)```/);
  if (!jsonMatch) return { formatted: content, isJson: false };

  try {
    const data = JSON.parse(jsonMatch[1]);
    const lines: string[] = [];
    for (const [key, value] of Object.entries(data)) {
      if (key === 'is_finished') continue;
      const label = dataLabels[key] || key;
      const val = valueLabels[String(value)] || String(value);
      lines.push(`${label}: ${val}`);
    }
    return { formatted: lines.join('\n'), isJson: true };
  } catch {
    return { formatted: content, isJson: false };
  }
}

function formatTime(dateStr: string) {
  const d = new Date(dateStr);
  return d.toLocaleString('ru-RU', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' });
}

function EventCard({ event }: { event: UserEvent }) {
  const isFunnel = event.event_type === 'funnel_message';
  const info = isFunnel ? null : eventButtonLabels[event.event_data];
  const label = isFunnel
    ? (funnelStageLabels[event.event_data] || event.event_data)
    : (info?.label || event.event_data);
  const botResponse = info?.botResponse || '';
  const Icon = isFunnel ? Mail : MousePointerClick;

  return (
    <div className="flex flex-col gap-1 my-1">
      {/* User pressed button */}
      <div className="flex justify-end">
        <div className="flex items-center gap-2 max-w-[85%] rounded-2xl px-3.5 py-2 bg-accent/50 border border-accent rounded-br-sm">
          <Icon className="w-3.5 h-3.5 text-primary shrink-0" />
          <div className="text-sm">
            <span className="text-foreground font-medium">
              {isFunnel ? label : `Нажал: "${label}"`}
            </span>
          </div>
          <span className="text-[10px] text-muted-foreground shrink-0 ml-1">
            {formatTime(event.created_at)}
          </span>
        </div>
      </div>
      {/* Bot response */}
      {botResponse && (
        <div className="flex justify-start">
          <div className="flex items-center gap-2 max-w-[85%] rounded-2xl px-3.5 py-2 bg-muted/50 border border-border rounded-bl-sm">
            <Bot className="w-3.5 h-3.5 text-muted-foreground shrink-0" />
            <span className="text-sm text-muted-foreground">{botResponse}</span>
          </div>
        </div>
      )}
    </div>
  );
}

export function ChatHistory({ sessionId }: ChatHistoryProps) {
  const { messages, loading: chatLoading, error: chatError } = useChatHistory(sessionId);
  const { events, loading: eventsLoading, error: eventsError } = useUserEvents(sessionId);
  const [showAll, setShowAll] = useState(false);

  const loading = chatLoading || eventsLoading;
  const error = chatError || eventsError;

  const timeline = useMemo(() => {
    const items: TimelineItem[] = [];

    // Add chat messages (convert callback phrases to button events)
    messages
      .filter((msg) => msg.content && msg.content.trim() !== '')
      .forEach((msg) => {
        const btnLabel = CALLBACK_PHRASES[msg.content.trim()];
        if (btnLabel) {
          items.push({ kind: 'button', id: msg.id, label: btnLabel });
        } else {
          items.push({ kind: 'message', id: msg.id, type: msg.type, content: msg.content });
        }
      });

    // Add events
    events.forEach((evt) => {
      items.push({ kind: 'event', event: evt });
    });

    return items;
  }, [messages, events]);

  const visible = showAll ? timeline : timeline.slice(-INITIAL_COUNT);
  const hasMore = timeline.length > INITIAL_COUNT && !showAll;

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8">
        <div className="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  if (error) {
    return <div className="text-center py-4 text-muted-foreground text-sm">Не удалось загрузить данные</div>;
  }

  if (timeline.length === 0) {
    return <div className="text-center py-8 text-muted-foreground text-sm">История пуста</div>;
  }

  return (
    <div className="space-y-2">
      {hasMore && (
        <Button variant="ghost" size="sm" className="w-full text-primary" onClick={() => setShowAll(true)}>
          Показать все ({timeline.length})
        </Button>
      )}
      {visible.map((item) => {
        if (item.kind === 'event') {
          return <EventCard key={`evt-${item.event.id}`} event={item.event} />;
        }
        if (item.kind === 'button') {
          return (
            <div key={`btn-${item.id}`} className="flex justify-end">
              <div className="flex items-center gap-2 max-w-[85%] rounded-2xl px-3.5 py-2 bg-accent/50 border border-accent rounded-br-sm">
                <MousePointerClick className="w-3.5 h-3.5 text-primary shrink-0" />
                <span className="text-sm text-foreground font-medium">Нажал: &quot;{item.label}&quot;</span>
              </div>
            </div>
          );
        }
        const { formatted, isJson } = formatJsonContent(item.content);
        return (
          <div key={`msg-${item.id}`} className={`flex ${item.type === 'human' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[85%] rounded-2xl px-3.5 py-2 ${
              item.type === 'human'
                ? 'bg-primary text-primary-foreground rounded-br-sm'
                : 'bg-card border border-border text-card-foreground rounded-bl-sm'
            }`}>
              {isJson && (
                <div className="flex items-center gap-1.5 mb-1">
                  <ClipboardList className="w-3.5 h-3.5 text-primary" />
                  <span className="text-xs font-medium text-primary">Собранные данные</span>
                </div>
              )}
              <div className="text-sm whitespace-pre-wrap break-words">{formatted}</div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
